version: '2'
services:
  cassandra1:
    image: cassandra:2.2
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    environment:
      JVM_OPTS: "-Djava.rmi.server.hostname=172.16.238.10"
      LOCAL_JMX: "no"
    volumes:
      - ./jmxremote.password:/etc/cassandra/jmxremote.password

  cassandra2:
    image: cassandra:2.2
    networks:
      app_net:
        ipv4_address: 172.16.238.11
    environment:
      CASSANDRA_SEEDS: "172.16.238.10"

  cassandra3:
    image: cassandra:2.2
    networks:
      app_net:
        ipv4_address: 172.16.238.12
    environment:
      CASSANDRA_SEEDS: "172.16.238.10"

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
